// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OutMessage.proto

// Protobuf Java Version: 4.26.0
package com.chen.proto;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person people = 1;</code>
   */
  java.util.List<com.chen.proto.Person> 
      getPeopleList();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  com.chen.proto.Person getPeople(int index);
  /**
   * <code>repeated .Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  java.util.List<? extends com.chen.proto.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  com.chen.proto.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
